### ISSUE TITLE
Does not take in new urls

### ISSUE THREAD

**Issue by LewisDick** [LewisDick/4chan-Image-Scraper#1]
When asked if you want to scrape a new thread, it scrapes the previous link again

**Comment by theslavicbear** [comment]
I do not get this issue on Ubuntu 18.10 with Python 3.6.7. It is possible that I unknowingly fixed this issue.

**Comment by LewisDick** [comment]
This was something I observed a while back, but haven't bothered to look at since I noted it. I'll see if I can reproduce the bug at some point later, once I'm more free.

The issue occure on Windows 10, Python 3.6.*
